# docker-compose.yml

version: '3.8'
services:
    starter-postgres:
        container_name: album-postgres
        image: postgres:latest
        environment:
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=123123"
            - "POSTGRES_HOST_AUTH_METHOD=trust"
            - "POSTGRES_DB=album-postgres"
            - "PGDATA=/var/lib/postgresql/data/pgdata" # Critical for Postgres to work in the container
        volumes:
            - postgres:/var/lib/postgresql/data
        hostname: localhost
        ports:
            - '5432:5432'
        restart: unless-stopped

    redis:
        image: 'redis:alpine'
        ports:
            - 6379:6379

volumes:
    postgres:
